#eureka:
#    client:
#        fetch-registry: true
#        register-with-eureka: true
#        service-url:
#            defaultZone: http://localhost:8184/eureka/

spring:
    application:
        name: configserver
    cloud:
        config:
            server:
                git:
                    force-pull: true
                    uri: https://github.com/debmalyap/config-server-repo.git