eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://localhost:9091/eureka/
server:
    port: 8085
spring:
    application:
        name: zuul-service
zuul:
    routes:
        track:
            url: http://localhost:8999
        user:
            url: http://localhost:8909